services:
  - type: web
    name: hackid-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: PYTHONPATH
        value: backend
      - key: PYTHON_VERSION
        value: 3.11.0
